<a href="https://colab.research.google.com/github/benishshrestha66/Projects/blob/main/BS%20to%20AD%20Date%20change.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install plotly pandas openpyxl -q
!pip install nepali_datetime -q

In [ ]:
from google.colab import files
uploaded= files.upload()

Saving sabina working.xlsx to sabina working (2).xlsx

In [ ]:
import pandas as pd
import nepali_datetime as nd

In [ ]:
df = pd.read_excel("sabina working.xlsx", header=1 )

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   2083-01-18 00:00:00  29 non-null     datetime64[ns]
 1   B.No.3013            29 non-null     object
 2   6198                 27 non-null     float64
 3   Unnamed: 3           2 non-null      float64
 4   398286               29 non-null     int64
dtypes: datetime64[ns](1), float64(2), int64(1), object(1)
memory usage: 1.3+ KB

In [ ]:
df.head()

  2083-01-18 00:00:00  B.No.3013     6198  Unnamed: 3  398286
0          2083-01-18  B.No.3014   3830.0         NaN  402116
1          2083-01-18  B.No.3015   1310.0         NaN  403426
2          2083-01-20  B.No.3016   6948.0         NaN  410374
3          2083-01-22  B.No.3017    370.0         NaN  410744
4          2083-01-25  B.No.3018  11043.0         NaN  421787

In [ ]:
df = pd.read_excel("sabina working.xlsx", dtype={"Nepali Date": str}, header=1)

In [ ]:
df.columns = df.columns.str.strip()

In [ ]:
import pandas as pd
import nepali_datetime as nd

df = pd.read_excel("sabina working.xlsx")

def bs_to_ad(bs_date):
    try:
        if isinstance(bs_date, str):
            year, month, day = map(int, bs_date.split("-"))
        else:  # already a datetime/Timestamp object
            year, month, day = bs_date.year, bs_date.month, bs_date.day
        return nd.date(year, month, day).to_datetime_date()
    except Exception as e:
        print(f"FAILED: {bs_date} -> {e}")
        return None

df["ad_date"] = df["Date"].apply(bs_to_ad)

# Format as month/day/year, e.g. 4/1/2026
df["ad_date"] = df["ad_date"].apply(lambda d: d.strftime("%m/%d/%Y") if pd.notna(d) else None)

print(df)
print("Failed rows:", df["ad_date"].isna().sum())

In [ ]:
df.head()

        Date Particulars  Dr Amount  Cr Amount  Balance     ad_date
0 2083-01-18   B.No.3013     6198.0        NaN   398286  05/01/2026
1 2083-01-18   B.No.3014     3830.0        NaN   402116  05/01/2026
2 2083-01-18   B.No.3015     1310.0        NaN   403426  05/01/2026
3 2083-01-20   B.No.3016     6948.0        NaN   410374  05/03/2026
4 2083-01-22   B.No.3017      370.0        NaN   410744  05/05/2026

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         30 non-null     datetime64[ns]
 1   Particulars  30 non-null     object
 2   Dr Amount    28 non-null     float64
 3   Cr Amount    2 non-null      float64
 4   Balance      30 non-null     int64
 5   ad_date      30 non-null     datetime64[ns]
dtypes: datetime64[ns](2), float64(2), int64(1), object(1)
memory usage: 1.5+ KB

In [ ]:
df.head(5)

        Date Particulars  Dr Amount  Cr Amount  Balance    ad_date
0 2083-01-18   B.No.3013     6198.0        NaN   398286 2026-05-01
1 2083-01-18   B.No.3014     3830.0        NaN   402116 2026-05-01
2 2083-01-18   B.No.3015     1310.0        NaN   403426 2026-05-01
3 2083-01-20   B.No.3016     6948.0        NaN   410374 2026-05-03
4 2083-01-22   B.No.3017      370.0        NaN   410744 2026-05-05

In [ ]:
from google.colab import files

df.to_excel("output.xlsx", index=False)
files.download("output.xlsx")